<a href="https://colab.research.google.com/github/JaniceShirley/ML_Basics/blob/main/DS_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creation of numpy array

In [ ]:
# ✅ (a) Creating Array from List
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

#✅ (b) Creating 2D Array
b= np.array([[4,5,6],[6,7,8]])
print(b)

#✅ (c) Zeros array
c=np.zeros((3,4))
print(c)

#✅ (d) ones array
d=np.ones((4,4))
print(d)

#✅ (e) array using - arange()
e= np.arange(0,11,2)
print(e)

#✅ (f) linespace array
f= np.linspace(0,10,5)
print(f)



[1 2 3 4]
[[4 5 6]
 [6 7 8]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0  2  4  6  8 10]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
✅ NumPy Array Attributes

In [ ]:
import numpy as np
arr= np.array([[1,2,3],[4,6,8]])
print(arr)


###🔹 1️⃣ ndim ---Returns the number of dimensions of the array.
print("Dimension=",arr.ndim)

###🔹 2️⃣ shape---Returns the no of rows and columns.
print("Shape=",arr.shape)

###🔹 3️⃣ size---Returns total number of elements in the array.
print("Size=",arr.size)

###🔹 4️⃣ dtype---Returns the data type of array elements.
print("Datatype=",arr.dtype)

###🔹 5️⃣ itemsize--- Returns the size on element.
print("Itemsize=",arr.itemsize)

###🔹 6️⃣ nbytes---Returns the total size.
print("Nbytes=",arr.nbytes)


[[1 2 3]
 [4 6 8]]
Dimension= 2
Shape= (2, 3)
Size= 6
Datatype= int64
Itemsize= 8
Nbytes= 48


In [ ]:
####Basic Array Operations

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])

###1 ---Addition
print("sum=",a+b)

###2 ---Subtraction
print("Diff=",a-b)

###3 ---Multiplication
print("Mul=",a*b)

###4 ---Division
print("div=",a/b)

###4 ---Power
print("Power=",a**b)


sum= [ 6  8 10]
Diff= [-4 -4 -4]
Mul= [ 5 12 21]
div= [0.2        0.33333333 0.42857143]
Power= [   1   64 2187]


In [ ]:
###✅ NumPy Aggregate Functions
Aggregate functions are used to perform calculations
on array elements
such as sum, average, maximum, and minimum.

In [ ]:
import numpy as np

a = np.array([16, 25, 33, 40])

print("Maximum=", a.max())
print("Minimum=", a.min())
print("Sum=", a.sum())
print("Mean=", a.mean())
print("Standard deviation=", a.std())
print("Variance=", a.var())

Maximum= 40
Minimum= 16
Sum= 114
Mean= 28.5
Standard deviation= 8.958236433584458
Variance= 80.25


In [ ]:
###✅ Indexing in NumPy
* Indexing is used to access specific elements in a NumPy array.
* It works using the position (index) of elements.
* Indexing can be done for both 1D and multidimensional arrays.
* In NumPy, indexing starts from 0.

In [ ]:
###✅ 1️⃣ Indexing in 1D Array
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print("4th element=",a[3])
print("5th element=",a[-1])

###✅ 2️⃣ Indexing in 2D Array
b = np.array([[1, 2, 3],[4, 5, 6]])
print("row 2 column 2 element=",b[1,1])
print("row 1 column 3 element=",b[0,2])

4th element= 40
5th element= 50
row 2 column 2 element= 5
row 1 column 3 element= 3


In [ ]:
###✅ Slicing in NumPy
* Slicing is used to access a range of elements from an array.
* It allows selecting multiple elements at once.
* Syntax:
array[start:end]


In [ ]:
###✅ 1️⃣ Slicing in 1D Array
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print(a[1:4:2])
print(a[:3])

###✅ 2️⃣ Slicing in 2D Array
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b[0:2, 1:3])
print(b[:,1]) ## print only second column
print(b[1,:]) ## print only 2nd row


[20 40]
[10 20 30]
[[2 3]
 [5 6]]
[2 5]
[4 5 6]


In [ ]:
###✅ Reshaping in NumPy
* Reshaping means changing the shape or dimensions of a NumPy array without changing its data.
* It is done using the reshape() function.
* The total number of elements before and after reshaping must remain the same.
* Reshaping is used to convert arrays from one dimension to another, such as 1D to 2D or 2D to 3D.
* NumPy also provides:
    * flatten() → converts array into 1D array
    * ravel() → converts array into 1D array

SyntaxError: invalid decimal literal (3854604812.py, line 5)

In [ ]:
####✅ Example for Reshaping in NumPy

##Example 1: Reshaping 1D Array to 2D Array
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3) #(rows nd columns)
print(b)

print("#####")
##Example 2: Reshaping into 3D Array
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(3, 1, 2) # 3 block, 1 row and 2 columns in each block
print(b)

[[1 2 3]
 [4 5 6]]
#####
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [ ]:
###✅ Pandas Series and DataFrame

In [ ]:
✅ What is a Series?

A Series is a one-dimensional labeled array in Pandas.

* Holds 1D data
* Has index and values
* Can store numbers, strings, dates, etc.

In [ ]:
### Example
import pandas as pd
s1 = pd.Series([10, 20, 30, 40])
s2 = pd.Series([90, 85, 88], index=['Math', 'Science', 'English'])

print(s1)
print(s2)

0    10
1    20
2    30
3    40
dtype: int64
Math       90
Science    85
English    88
dtype: int64


In [ ]:
## Series operation

# 1--access data
import pandas as pd
s = pd.Series([90, 85, 88], index=['Math', 'Science', 'English'])
print(s)
print("####Acess data")
print(s['Math'])

#2----Statistics
print("#####Statistical")
print(s.mean())
print(s.min())
print(s.max())

Math       90
Science    85
English    88
dtype: int64
####Acess data
90
#####Statistical
87.66666666666667
85
90


In [ ]:
###🔹 2️⃣ Pandas DataFrame

In [ ]:
✅ What is a DataFrame?

A DataFrame is a two-dimensional labeled data structure in Pandas.

* Contains rows and columns
* Similar to Excel sheet or SQL table
* Can store multiple data types

In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 30, 28],
    'Score': [85, 90, 88]
}
df = pd.DataFrame(data)
df.index=['a','b','c']
print(df)

###Access Columns
print("Access Columns")
print(df['Name'])

###Access rows
print("Access rows")
print(df.loc['b'])## using labelledindex
print(df.iloc[2])## using position

##Rename columns
print("Rename columns")
df.rename(columns={"Score": "Marks"}, inplace=True)

print(df)


      Name  Age  Score
a    Alice   24     85
b      Bob   30     90
c  Charlie   28     88
Access Columns
a      Alice
b        Bob
c    Charlie
Name: Name, dtype: object
Access rows
Name     Bob
Age       30
Score     90
Name: b, dtype: object
Name     Charlie
Age           28
Score         88
Name: c, dtype: object
Rename columns
      Name  Age  Marks
a    Alice   24     85
b      Bob   30     90
c  Charlie   28     88


In [ ]:
### Filtering, sorting, grouping
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 20, 21],
    "Score": [80, 90, 95, 100]
}
df = pd.DataFrame(data)
print(df)

#1---filtering
print("filtering")
print(df[df["Age"]>20])

# 2---Sorting
print("Sorting")
print(df.sort_values(by="Score",ascending=False))

#3---Grouping
##👉 “Group people by Age and find the average Score for each age.”
print("Grouping")
print(df.groupby("Age")["Score"].mean())

      Name  Age  Score
0    Alice   20     80
1      Bob   21     90
2  Charlie   20     95
3    David   21    100
filtering
    Name  Age  Score
1    Bob   21     90
3  David   21    100
Sorting
      Name  Age  Score
3    David   21    100
2  Charlie   20     95
1      Bob   21     90
0    Alice   20     80
Grouping
Age
20    87.5
21    95.0
Name: Score, dtype: float64


In [ ]:
###✅ Rank and Sort in Pandas

🔹 1️ Sorting in Pandas

✅ What is Sorting?
Sorting means arranging data in:
* Ascending order
* Descending order
* syntax: sort_values()

🔹 2️⃣ Ranking in Pandas
✅ What is Ranking?
Ranking assigns position numbers based on values.
* syntax: rank()

These are important operations used in:
* Data analysis
* Leaderboards
* Business reporting
* Top-k selection


In [94]:
###✅ Example for Sorting
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Marks": [85, 95, 90]
}
df = pd.DataFrame(data)
print(df.sort_values(by="Marks"))
print("Descending")
print(df.sort_values(by="Marks", ascending=False))



      Name  Marks
0    Alice     85
2  Charlie     90
1      Bob     95
Descending
      Name  Marks
1      Bob     95
2  Charlie     90
0    Alice     85


In [110]:
###✅ Example for Ranking
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie","lily"],
    "Marks": [85, 95, 90,90]
}
df = pd.DataFrame(data)
df["Rank1"]= df["Marks"]. rank() ## lower marks gets 1st rank
print(df)
df["Rank2"]= df["Marks"]. rank(ascending=False) ## highest marks get 1st rank
print(df)

##✅ Ranking Methods
#1---Dense Rank----No gaps in ranking.
df["Dense_Rank"] = df["Marks"].rank(method="dense", ascending=False)
print(df)

#2---Min Rank---Same minimum rank for ties.
df["Min_Rank"] = df["Marks"].rank(method="min", ascending=False)
print(df)

#3---Max Rank---Same maximum rank for ties.
df["Max_Rank"] = df["Marks"].rank(method="max", ascending=False)
print(df)

#4--First Rank---This gives ranks based on the order of appearance when values are tied.
df["First_rank"]=df["Marks"].rank(method="first", ascending=False)
print(df)

      Name  Marks  Rank1
0    Alice     85    1.0
1      Bob     95    4.0
2  Charlie     90    2.5
3     lily     90    2.5
      Name  Marks  Rank1  Rank2
0    Alice     85    1.0    4.0
1      Bob     95    4.0    1.0
2  Charlie     90    2.5    2.5
3     lily     90    2.5    2.5
      Name  Marks  Rank1  Rank2  Dense_Rank
0    Alice     85    1.0    4.0         3.0
1      Bob     95    4.0    1.0         1.0
2  Charlie     90    2.5    2.5         2.0
3     lily     90    2.5    2.5         2.0
      Name  Marks  Rank1  Rank2  Dense_Rank  Min_Rank
0    Alice     85    1.0    4.0         3.0       4.0
1      Bob     95    4.0    1.0         1.0       1.0
2  Charlie     90    2.5    2.5         2.0       2.0
3     lily     90    2.5    2.5         2.0       2.0
      Name  Marks  Rank1  Rank2  Dense_Rank  Min_Rank  Max_Rank
0    Alice     85    1.0    4.0         3.0       4.0       4.0
1      Bob     95    4.0    1.0         1.0       1.0       1.0
2  Charlie     90    2.5    2.5  