In [3]:
import numpy as np

In [22]:
a= np.array([1,2,3],dtype='int32')
print(a)
b=np.array([[9.0,8.0,7],[6.0,5.0,4.0]])
print(b)


[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [23]:
a.ndim

1

In [24]:
b.shape

(2, 3)

In [25]:
#get type
a.dtype

dtype('int32')

In [28]:
#byte size of 1 element 
a.itemsize
b.itemsize

8

In [27]:
#total byte size
a.size * a.itemsize

12

In [ ]:
#INDEXING AND SLICING 